### ISSUE TITLE
RDP connection : Not able to connect to rdp when converted to wsl2

### ISSUE THREAD

**Issue by KushalSM** [DesktopECHO/kWSL#1]
Hi @DesktopECHO 

I have tried the wsl 1 version and it works beautifully and I am able to rdp into it perfectly.
When I converted it to wsl 2 i got no errors anywhere but when i followed you guide of what changes to make, i tried to connect to the RDP session it showed this error,
![Screenshot (134)](https://user-images.githubusercontent.com/64859307/89288379-2c3d0100-d673-11ea-836b-dcedc6c26c3e.png)

My laptop name is KUSHALSM-LAPTOP

Idk what to do, pls help me!!!!

**Comment by DesktopECHO** [comment]
*EDIT: Before doing any of this first make sure the Init task is running after the conversion to WSL2.  In your case that would be:
`schtasks /run /tn Kushal_KDE`

Hi there,

Perhaps you have an issue with multicast DNS.  

Try this -- Open a console to your Linux instance and run:

`hostname -I`

It will return the IP address of your WSL instance - Use that instead of the hostname for your RDP connection.
Let me know how things go for you.

Cheers,
D.

**Comment by KushalSM** [comment]
By init do you mean the the init task you must run before rdping int the wsl gui desktop?

Edit:-
Cheers!!!
It works, the solution you have me was very helpful and I am able to Firefox and chrome and even the audio is working even though there is a issue of the video and audio not syncing..

The main point is that wsl 2 support works and with audio included..

Hats off to you..

Cheers again :D

**Comment by DesktopECHO** [comment]
Hello thank you for the kind words.  Glad to hear things are working as expected.   If you go to youtube and play a video with the bundled version of Mozilla browser, do you still lose audio sync?  I have not seen that issue unless you are connecting to the WSL instance from another machine on your internal network.   

Cheers,
D.

**Comment by KushalSM** [comment]
what do you mean by "bundled version of mozilla browser", Iam kind of a newbie linux user but love it so can you pleases tell in detail...

And also could you help to create a script that laucnches the rdp connection with the changed ip address. If not, its fine and I will try to create one and share it with you.

**Comment by KushalSM** [comment]
By the way to help you, I have told people in youtube in comments section to go to you repo and try both xWSL and kWSL. Is it fine??

**Comment by DesktopECHO** [comment]
> what do you mean by "bundled version of mozilla browser", Iam kind of a newbie linux user but love it so can you pleases tell in detail...

Try using Mozilla Seamonkey as your browser: 
![image](https://user-images.githubusercontent.com/33142753/89612545-6c100e00-d856-11ea-9be8-4473c322f78a.png)

> By the way to help you, I have told people in youtube in comments section to go to you repo and try both xWSL and kWSL. Is it fine??

Please do!

**Comment by KushalSM** [comment]
I have no problem with seamonkey.
I was talking about firefox latest version in wsl 2. At the first there was no audio and video sync at first but now it is ok. Must have been a first time issue..

**Comment by KushalSM** [comment]
@DesktopECHO 
Also how did you get the kwsl.local to work?
Because it is better to do that instead of everytime checking the ip addr and the connecting to it??

Edit:-
I actually got the kwsl.local working
I had put by distro name as KDE-Plasma, so instead of kwsl.local I had to change it to KDE-Plasma.local. So you can edit the README.md file and tell that they have to put the distro name they chose when running the batch file..

**Comment by KushalSM** [comment]
Thx for updating the README.md

Cheers 👍
