### ISSUE TITLE
Possibility to run single linux apps with native titlebars?

### ISSUE THREAD

**Issue by VPraharsha03** [DesktopECHO/kWSL#10]
Is it possible to run single apps with linux titlebars instead of a full desktop when using RDP ? Something like how [winapps](https://github.com/Fmstrat/winapps) has implemented...

Only some/few of the apps (eg: nautilus & gedit) have their own titlebars and most of them have their titlebar drawn/inherited from the OS

**Comment by DesktopECHO** [comment]
Sorry, no.  I think you're looking for something like [WSLg](https://github.com/microsoft/wslg)
