### ISSUE TITLE
WSL drive mount issue

### ISSUE THREAD

**Issue by douglangille** [DesktopECHO/kWSL#13]
Script throwing this message on a fresh deploy of Win11. For both xWSL and kWSL.

```
An error occurred mounting one of your file systems. Please run 'dmesg' for more details.
```

Ran on identical config last week. Today? not so much. It's repeatable (for me) on a clean install of Win11.

I can provide whatever info needed. Just don't know what's needed.

**Comment by DesktopECHO** [comment]
Hi, can you try running:
``wsl --set-default-version 1``
...then launch the script and let me know how things go.

**Comment by douglangille** [comment]
Thanks for getting back so quickly. #sadtrombone Same result. 
```
[kWSL Installer 20211110]

Enter a unique name for your kWSL distro or hit Enter to use default.                                                   Keep this name simple, no space or underscore characters [kWSL]: NEON                                                   Port number for xRDP traffic or hit Enter to use default [3399]:                                                        Port number for SSHd traffic or hit Enter to use default [3322]:                                                        Set a custom DPI scale, or hit Enter for Windows default [1]:                                                           [Not recommended!] Type X to eXclude from Windows Defender:

Installing kWSL Distro [NEON] to "C:\Users\douglangille\NEON"
This will take a few minutes, please wait...

[15:39:50] Installing Ubuntu 20.04 LTS (~1m30s)
[15:39:52] Git clone and update repositories (~1m15s)
An error occurred mounting one of your file systems. Please run 'dmesg' for more details.
An error occurred mounting one of your file systems. Please run 'dmesg' for more details.
An error occurred mounting one of your file systems. Please run 'dmesg' for more details.
An error occurred mounting one of your file systems. Please run 'dmesg' for more details.
An error occurred mounting one of your file systems. Please run 'dmesg' for more details.
An error occurred mounting one of your file systems. Please run 'dmesg' for more details.
An error occurred mounting one of your file systems. Please run 'dmesg' for more details.
[15:39:54] Remove un-needed packages (~1m30s)
```

**Comment by DesktopECHO** [comment]
That's a WSL2-type of error so I'm genuinely confused.
Hate to ask, have you rebooted your PC?
Also, create a user on your PC, login as that user, and try installing.  Maybe profile related?

**Comment by douglangille** [comment]
:)  yeah, clean boot. and recreated on a clean install (for kicks) with a fresh profile.
I rebuild this machine (way too often) as it's a test bed so I follow the same build notes.
But your note about that being a v2 error is a clue. I _do_ have a v2 Ubuntu instance that I always install first. I'll convert to v1 and/or uninstall it. Then I'll reboot cleanly.
Standby for results. Thanks.

**Comment by douglangille** [comment]
Still fails. Current state (before cleaning up after the failed script)

```
PS C:\Users\douglangille> wsl --status
Default Distribution: NEON
Default Version: 1

Windows Subsystem for Linux was last updated on 2022-02-07
WSL automatic updates are on.

Kernel version: 5.10.60.1
PS C:\Users\douglangille> wsl -l -v
  NAME    STATE           VERSION
* NEON    Running         1
PS C:\Users\douglangille>
```

**Comment by DesktopECHO** [comment]
Do you have a ``%USERPROFILE%/.wslconfig`` file?  If so try without it.

**Comment by DesktopECHO** [comment]
One more question -- Are you able to install Ubuntu 20.04 from the store?  Can you confirm it is WSL1 with a ``uname -a``

**Comment by douglangille** [comment]
Okay. Installed Ubuntu from Store.
No .wslconfig

```
PS C:\Users\douglangille> wsl -l -v
  NAME      STATE           VERSION
* NEON      Stopped         1
  Ubuntu    Running         1
```
```
douglangille@UBIK:~$ uname -a
Linux UBIK 4.4.0-22000-Microsoft #1-Microsoft Fri Jun 04 16:28:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by DesktopECHO** [comment]
Hi what version of Windows 11 are you on?
There is a (known, fixed in insiders build) separate issue with Win11 causing a BSOD in WSL1.  So unless you're running an insider build, you will have a bad time :/
In any case let me know what your build number is and I'll try to recreate the issue.
#Maritimer

**Comment by douglangille** [comment]
Edition Windows 11 Enterprise
Version 21H2
Installed on ‎2022-‎02-‎07
OS build 22000.469
Experience Windows Feature Experience Pack 1000.22000.469.0

--
***@***.***
________________________________

**Comment by DesktopECHO** [comment]
Do you have the WSL2 update package from the Microsoft Store?  Can you try uninstalling it and any kernel updates to see how that goes?

**Comment by DesktopECHO** [comment]
Thanks for the bug report. 
I have re-created the issue:
![image](https://user-images.githubusercontent.com/33142753/152874382-f6d482da-90e4-4c10-985c-7a9235b074e4.png)
Well that sucks!  I am going to try and revert KB5008353...

**Comment by douglangille** [comment]
Yay! Glad it’s not just me. One never knows…
Thanks for all you do.
Happy to test whatever you’d like me to try.
Meanwhile, back out to chipping ice from, well, everything.

--
***@***.***
________________________________

**Comment by DesktopECHO** [comment]
Hi please give the latest update for kWSL a try when you get a chance.
Thanks,
D.

**Comment by douglangille** [comment]
Well, there ya go. It works now. Thank you. Looks like updating lxrunoffline did the trick.

I think this issue can be marked closed.

I still get a memory_management stopcode on first run but it’s nice and solid after a reboot.

--
***@***.***
________________________________

**Comment by DesktopECHO** [comment]
I just updated xWSL a few moments ago as well.
Looks like we also needed to change the download source from the MS-provided APPX package (which has changed and is now a bloated 800MB download) to the Ubuntu-sourced WSL .tar.gz image. 
The WIndows 11 BSOD Fix is available to insiders and I think will be generally available next month (I hope!)

**Comment by DesktopECHO** [comment]
BTW found some good reading on your blog, keep 'em coming.  And try not to freeze, I got fed up with east coast weather and moved to a little island in the middle of the ocean.
