### ISSUE TITLE
Not able to point the RDP file to new WSL2 instance

### ISSUE THREAD

**Issue by devmalya-b** [DesktopECHO/kWSL#14]
After a successfull installation of kWSL, I swtiched the default version of WSL to 2. Conversion was successful as well and so was the restart of Kwsl. But now I am not able to point the RDP file to the new WSL2 instance. Assume my laptop's name (in My PC properties) is LAPTOPXYZ, my username D, and my kWSL instance name is NeonWSL. 
- I have tried editing the settings of the RDP file and put LAPTOPXYZ-NeonWSL.local:3399 as the host address. Does not connect.
- I have tried typing LAPTOPXYZ-NeonWSL.local:3399 as a command in cmd and powershell and the kWSL console as well (elevated) with no results (which was a long shot but I tried it anyways). 

What am I supposed to do to point to the new WSL2 instance?

**Comment by devmalya-b** [comment]
Figured this out with go-wsl2-host, but this way even after scheduling the task for startup- the xrdp service does not initiate automatically. Added the following script in Startup folder of windows to start it when I start my device:
```
wsl nohup sudo service xrdp start
```

Works perfectly now. Can just boot up windows and click on the saved RDP file (pointing to neonwsl.wsl:13399) and it'll pop KDE.

**Comment by DesktopECHO** [comment]
Hi good to hear you have it sorted. 
Are you on Windows 10 or 11?  I just spun up a Neon instance on a physical Win10 21H2 box, converted to WSL2 per instructions and connected to the WSL2 instance without issue.

**Comment by devmalya-b** [comment]
I'm on Windows 10, not sure why did I face the issue. What exactly is the command that you exactly used to point the RDP instance to the new WSL host on port 3399?

**Comment by DesktopECHO** [comment]
My computer name is Z440 and instance name was WinKDE, using port 3399.  So after converting to WSL2 I changed it from Z440:3399 to Z440-WinKDE.local
