### ISSUE TITLE
Too many bugs!

### ISSUE THREAD

**Issue by devmalya-b** [DesktopECHO/kWSL#15]
Really loved the distro installation, but seems that there are too many bugs. My desktop env keeps crashing repeatedly (goes black but the apps still keep running) but since there is no taskbar or manager, I can't control anything. 

I even added the full neon environment but this still keeps happening. While I understand this may be more of KDE's fault, is there a solution? Or is there a way to install Gnome in a similar way, without a container or bottle?

**Comment by DesktopECHO** [comment]
Hi, I'm seeing similar issues.  Give [this branch](https://github.com/DesktopECHO/kWSL/compare/master...picom) a try and let me know if the situation gets any better:

`PowerShell -executionpolicy bypass -command "wget https://github.com/DesktopECHO/kWSL/raw/picom/kWSL.cmd -UseBasicParsing -OutFile kWSL.cmd ; .\kWSL.cmd"`

**Comment by DesktopECHO** [comment]
Updated master with stability improvements.

**Comment by devmalya-b** [comment]
@DesktopECHO so is there no Gnome install as such? I don't wanna reinstall the whole KDE distro just for it to be crashing again! Would be really cool if I could get a much more stable DE that is more functional than XFCE!

**Comment by DesktopECHO** [comment]
> EDIT: Looks like I am not connected to the D-Bus server when I try to restart the plasmashell

After a fresh install you're still having crashes?

**Comment by devmalya-b** [comment]
I haven't done a fresh install, since I already have too much data on this instance. 

Are there any possible commands I could run on my install to fix the crashes? Have been using `killall plashmashell; plasmashell & ` as a temporary fi to restart the panel.

**Comment by DesktopECHO** [comment]
The changes that improve stability are [here](https://github.com/DesktopECHO/kWSL/commit/7459d428b62eaaba61ac1114d853fb46cd2296a8), but I still recommend a fresh install. 

You can also spin-up another KDE instance and run it side-by-side with your exisitng install to determine if it works better (just give it a unique name and select different ports from the original install)
