### ISSUE TITLE
Log Out on kWSL does not terminate anything 

### ISSUE THREAD

**Issue by devmalya-b** [DesktopECHO/kWSL#18]
@DesktopECHO According to your last suggestion, I switched the `start-sleep` value to 15 first. It worked for a few days. The xrdp-sessman would terminate and so would the instance. But then it stopped working. Same happened with 30 and now 60. Now clicking on the logout does nothing except kill close the RDP window. How do I change that?

**Comment by DesktopECHO** [comment]
Check this out: 
https://www.reddit.com/r/bashonubuntuonwindows/comments/yd56hm/stop_wsl_from_the_linux_terminal/

I don't have anything to add past trying that utility (I've not tested it so YMMV)
