### ISSUE TITLE
How to edit xrdp login screen??

### ISSUE THREAD

**Issue by KushalSM** [DesktopECHO/kWSL#2]
@DesktopECHO 
could you tell us how to edit xrdp login screen???

EDIT:-

By the way to help you, I have told people in youtube in comments section to go to you repo and try both xWSL and kWSL. Is it fine??

**Comment by DesktopECHO** [comment]
Can your ping your KDE Instance from Windows?
`ping KUSHALSM-LAPTOP-kwsl.local`

Feel free to spread the word, thanks!
D.

**Comment by KushalSM** [comment]
@DesktopECHO 

When I execute the command you gave me, I get this error,
Ping request could not find host KUSHALSM-LAPTOP-kwsl.local. Please check the name and try again.
![Screenshot (135)](https://user-images.githubusercontent.com/64859307/89626861-a78ef480-d8b7-11ea-81b9-7d4407d7de77.png)

**Comment by KushalSM** [comment]
I dont have problem connecting to my rdp connection. 
What my doubt was like how you added kWSL with KDE Plasma Symbol in the login screen, I wanted to know how you edited it because I search in you tube and understood it but I was not able to find bitmap images and when i uploaded a file it does not show the pic.
That is why asked how you edited the xrdp login screen.

**Comment by DesktopECHO** [comment]
Ah ok I think I understand now.  Did you mean this?

![image](https://user-images.githubusercontent.com/33142753/89654899-b8cc0700-d89f-11ea-91df-f87512b8f454.png)

It's located at /usr/share/xrdp/xrdp_logo.bmp

**Comment by DesktopECHO** [comment]
> @DesktopECHO
> 
> When I execute the command you gave me, I get this error,
> Ping request could not find host KUSHALSM-LAPTOP-kwsl.local. Please check the name and try again.

Make sure the scheduled task is running and please post the contents of  ` cat /var/log/daemon.log | grep avahi` to see if we can find out why mDNS isn't working for you.  I'm not sure I can troubleshoot that for you but we can try.  

EDIT: Please create a new Issue in GitHub for this problem.

**Comment by KushalSM** [comment]
> @DesktopECHO
> 
> When I execute the command you gave me, I get this error,
> Ping request could not find host KUSHALSM-LAPTOP-kwsl.local. Please check the name and try again.
> ![Screenshot (135)](https://user-images.githubusercontent.com/64859307/89626861-a78ef480-d8b7-11ea-81b9-7d4407d7de77.png)

@DesktopECHO 

It is fine I have no error since it is not and issue. I had changed the distro name where you it is asked in the batch script to enter a unique distro name i.e, I changed my distro name to "KDE_Plasma". so instead of KUSHALSM-LAPTOP-kwsl.local:3390, I should change it to KUSHALSM-LAPTOP-KDE-Plasma.local:3390.

So you can update the README.md to do this if they have changed their distro name when they ran the Batch script.

**Comment by KushalSM** [comment]
> Ah ok I think I understand now. Did you mean this?
> 
> ![image](https://user-images.githubusercontent.com/33142753/89654899-b8cc0700-d89f-11ea-91df-f87512b8f454.png)
> 
> It's located at /usr/share/xrdp/xrdp_logo.bmp

Thx got it!!

**Comment by KushalSM** [comment]
Thx for updating the README.md

Cheers 👍
