### ISSUE TITLE
22.04 Upgrade?

### ISSUE THREAD

**Issue by NullDev** [DesktopECHO/kWSL#20]
Is a 22.04 Rebase for kWSL planned? 
If I try to upgrade via KDE Upgrader I first get 

> Please install all upgrades first

Upon upgrading the held-back packages (`kactivitymanagerd kinfocenter libkf5activitiesstats1 xdg-desktop-portal`) I get: 

> Error executing command as another user: Not authorized

Finally, `do-release-upgrade` throws new errors:

> An unresolvable problem occurred while calculating the upgrade:
> This can be caused by:  
> \* Unofficial software packages not provided by Ubuntu

---

And a small question: Why is discover automatically started as root?

**Comment by DesktopECHO** [comment]
Hi, do you run the instance in WSL1 or WSL2?  

If it's WSL2, you can probably unhold those packages and try your upgrade again.
`apt-mark unhold kactivitymanagerd kinfocenter libkf5activitiesstats1 xdg-desktop-portal`

Otherwise, updated 22.04 packages would be needed to work around limitations in WSL1.   
One limitation is a lack of PackageKit (systemd) support so I replaced it with KDEsu, and the reason you see that warning in Discover.  Another is WSL1 can't deal with sqlite write-ahead logging so that has to get patched-out of kactiviymanager/stats.

**Comment by NullDev** [comment]
I ran it in WSL2, and I tried unholding the packages. I then received the second error I mentioned

> Error executing command as another user: Not authorized

Would a WSL2 only fork of kWSL be possible, without those limitations (and maybe 22.04 base)?
I feel like the WSL1 compatibility restricts it's potential quite a bit

**Comment by DesktopECHO** [comment]
Have you tried 'sudo' in front, like so?

`sudo apt-mark unhold kactivitymanagerd kinfocenter libkf5activitiesstats1 xdg-desktop-portal`

One day I'll look at rebasing, but this project was initially made for WSL1.

**Comment by NullDev** [comment]
Sorry, should've been more clear:
The unholding works just fine (yes, I used sudo)

But if I attempt to start the upgrade again (after unholding the packages), the KDE Upgrade GUI fails with 

> Error executing command as another user: Not authorized

**Comment by DesktopECHO** [comment]
Aha ok... sorry I've never gone through the KDE Upgrade GUI before so was a bit confused.
  
Sounds like the only thing holding you back is that you need to launch the utility with `kdesu` so it has adequate rights to upgrade the system.

**Comment by NullDev** [comment]
Ill give that a try later, thank you! 
I will also try to make a fork optimized for WSL2. Thank you for your support so far!

**Comment by NullDev** [comment]
Quick update: Unfortunately so far I wasn't able to produce a stable 22.04 build :/ 
Would be cool if this issue could remain open for the time being. Given that 20.04 support will be dropped in a couple of days
