### ISSUE TITLE
WSL2 Version + 22.04 Rebase

### ISSUE THREAD

**Issue by NullDev** [DesktopECHO/kWSL#23]
I just wanted to ask if a WSL2 version is planned? I tried forking the repo but wasn't able to produce a stable result (I sadly don't know much about WSL since I'm a Linux user, just kinda forced to use windows now). 
I'd really love to use this as daily driver. I just don't know how much work it would be to make a WSL2 script for the most recent KDE Neon (but I suppose a lot of WSL1 patches would be obsolete) 

So would a WSL2 Version of kWSL with KDE Neon 5.26 (Ubuntu 22.04) be possible? I'd be willing to sponsor this as well

**Comment by DesktopECHO** [comment]
You can convert the instance to WSL2 after install, but no further development of this is in the pipeline, sorry.
