### ISSUE TITLE
Recent activity

### ISSUE THREAD

**Issue by NullDev** [DesktopECHO/kWSL#24]
Hey 👋 
I just noticed that you're planning on a rework / update which is AWESOME :D 
After this project was in hiatus I decided I attempt to update it myself. It took a almost a year but it works now, there are just some minor  performance problems. In case you want to take a look: 

https://github.com/NullDev/kWSL/tree/echomaster

I dropped support for WSL1 with it thou but support the most recent neon now.
There are probably some unnecessary and stupid things in the code (Im by no means a WSL or Batch expert) but it works I guess

**Comment by DesktopECHO** [comment]
Hi... The latest build of the script runs in WSL1 or WSL2 (after converting) and includes the latest Neon user edition.   XRDP is faster as well.

**Comment by NullDev** [comment]
Welp, then my fork is obsolete :D 
Thank you for your work!
