### ISSUE TITLE
xRDP Problem: Missing text, wrong window size

### ISSUE THREAD

**Issue by h13World** [DesktopECHO/kWSL#27]
After running kWSL.cmd without any errors and starting the RDP connection from my Windows 11 Pro (23H2 Build: 22631.3374) client I get the following Plasma 6 experience:

![kWSL1](https://github.com/DesktopECHO/kWSL/assets/150487264/b82928fa-6b4e-4815-9701-a5cf2e64e9b7)

Also tried to connect via Chrome Remote Desktop. There I get the following prompt and after selecting: Plasma (X11) Plasma by KDE I only get a black screen.

<img width="455" alt="kWSL2" src="https://github.com/DesktopECHO/kWSL/assets/150487264/ef7780f2-ce16-40a8-a03f-4e21e071ec29">

**Comment by DesktopECHO** [comment]
That looks really messed up, all your fonts are missing...

Not sure why it's doing that.  I've never seen something like this occur.  Try spinning-up a new instance and see if the issue persists.  You can also try creating a new user and see if the problem is at the user account level or the full instance.

**Comment by h13World** [comment]
I found the mistake. It is a language/localization problem. I am from Austria and therefore I use the language and localization German (Austria).

<img width="366" alt="image" src="https://github.com/DesktopECHO/kWSL/assets/150487264/e41092dc-c375-4b8b-879d-895909bad7fd">

When you have to choose the custom DPI scale and use the default entry (1,5) there it uses "," because of the German localization and that's why it messes up everything.

If you instead use:
`Set a custom DPI scale, or hit Enter for Windows default [1,5]: 1.5`
everything works like expected.
