### ISSUE TITLE
Plasmashell won't start after kwsl reinstall

### ISSUE THREAD

**Issue by NekoNyanners** [DesktopECHO/kWSL#28]
So, I installed the new kWSL for 6.0 and everything worked perfectly fine. 
Then I wanted to delete my old WSL but removed the new kWSL by accident ;-;

So I went to just install it again and... It doesn't work anymore. 
The cursor style loads but I am met with a black screen. I can fire up the GUI terminal using CTRL + ALT + T 
and I can even start GUI applications like seamonkey from the terminal. But no taskbar, no background or anything. 
So I tried starting it myself 

`$ pkill plasmashell`
`$ plasmashell &`

```
kde.plasmashell: Aborting shell load: The activity manager daemon (kactivitymanagerd) is not running.
kde.plasmashell: If this Plasma has been installed into a custom prefix, verify that its D-Bus services dir is known to the system for the daemon to be activatable.
```

Doing `$ kactivitymanagerd` yields `kactivitymanagerd: command not found`
BUT doing `sudo apt install kactivitymanagerd` says `kactivitymanagerd is already the newest version (6.6.2-0xwsl1).`

I am pretty sure I didn't change anything between the initial install and the reinstall. I also wiped the folder, unregistered the wsl instance and everything. 

I tried the reinstall multiple times over last last couple of days. Always the same problem. 
Do you have any clue what could have went wrong?

**Comment by DesktopECHO** [comment]
Hi there, looks like a change upstream necessitated a rebuild of kactivitymanager.
I committed the changes to the repo a moment ago, so you should be able to run the installer and successfully get a desktop session.

**Comment by NekoNyanners** [comment]
Yep, works now! Thank you :)
