### ISSUE TITLE
File dialog broken on chrome

### ISSUE THREAD

**Issue by NekoNyanners** [DesktopECHO/kWSL#29]
I did something stupid. 

I installed the latest kWSL and converted it to WSL2 and started installing my stuff. 
Also downloaded stuff from chrome which worked fine. 

Then I wanted to just install `neon-all` but couldn't because a lot of stuff depended on `qt6-webengine` which is [marked as hold by kWSL](https://github.com/DesktopECHO/kWSL/blob/master/kWSL.cmd#L117).
So I thought lets just install it anway because whats the worst that could happen. 

aaaaaaaaand yea. I installed `neon-all` and apps that depend on `qt6-webengine` seem to work fine. But it came at a cost.
I cant download stuff from chrome anymore because it can't open the system file dialog. When I try to download something I get 

> ERROR:select_file_dialog_linux_portal.cc(760)] Portal returned error: org.freedesktop.DBus.Error.AccessDenied: Portal operation not allowed: Unable to open /proc/0/root

I'm not sure if they were there before but there are a lot of other errors as well: 

```
ERROR:browser_dm_token_storage_linux.cc(100)] Error: /etc/machine-id contains 0 characters (32 were expected).
ERROR:viz_main_impl.cc(198)] Exiting GPU process due to errors during initialization
ERROR:object_proxy.cc(576)] Failed to call method: org.kde.KWallet.isEnabled: object_path= /modules/kwalletd6: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
ERROR:kwallet_dbus.cc(112)] Error contacting kwalletd6 (isEnabled)
ERROR:object_proxy.cc(576)] Failed to call method: org.kde.KLauncher.start_service_by_desktop_name: object_path= /KLauncher: org.freedesktop.DBus.Error.ServiceUnknown: The name org.kde.klauncher was not provided by any .service files
ERROR:kwallet_dbus.cc(81)] Error contacting klauncher to start kwalletd6
ERROR:object_proxy.cc(576)] Failed to call method: org.kde.KWallet.close: object_path= /modules/kwalletd6: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
ERROR:kwallet_dbus.cc(502)] Error contacting kwalletd6 (close)
ERROR:atom_cache.cc(229)] Add WM_CHANGE_STATE to kAtomsToCache
ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
ERROR:command_buffer_proxy_impl.cc(131)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
ERROR:gl_utils.cc(424)] [.WebGL-0x598004b5400]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): GPU stall due to ReadPixels
```

Soooooo... Do I have to purge `qt6-webengine` along with all apps that depend on it or is there a workaround?

**Comment by DesktopECHO** [comment]
Can you try selecting "GTK" in appearance settings to get around this?

<img width="1134" alt="image" src="https://github.com/DesktopECHO/kWSL/assets/33142753/d5191bf5-725c-4b0d-aca8-2cb325adab54">

You can un-hold the packages, `apt-mark unhold qt6-webengine` and update, but anything using qt6-webengine will be slowed-down due to a bug in version 6.7.0.  

This is less of an issue in WSL2 where you can run Chrome-based browsers without issue, but in WSL1 the only decent and modern browser that works well is Falkon, and that uses qt6-webengine.

**Comment by NekoNyanners** [comment]
Same issue with GTK sadly 

![image](https://github.com/DesktopECHO/kWSL/assets/97849249/e0958699-6c37-4116-9d51-fc91e3246e5a)

Im using WSL2 for this instance

**Comment by DesktopECHO** [comment]
I think this will sort out your issue:

`sudo apt-get install --reinstall dbus ; sudo systemd-machine-id-setup ; sudo restartwsl`

Log back into the instance and the file dialog should work.

**Comment by NekoNyanners** [comment]
That did indeed work! Thank you so so much!!
I can't tell you enough how amazing this project is and how much pain it saved me ❤️
