### ISSUE TITLE
kWSL black screen & failure to start

### ISSUE THREAD

**Issue by ScarletLovell** [DesktopECHO/kWSL#3]
RDP launches but ends up in black screen.

I have done the following:

- Uninstalled WSL Ubuntu 20.04 LTS so that it doesn't interfere
- Reinstalled kWSL twice

Upgrading kWSL to WSL2 as-well results in kWSL no longer being able to open, even with changing RDP as the readme suggests.

Not entirely sure what information I could give to help this issue either

**Comment by DesktopECHO** [comment]
Hi There,

I updated the script to provide better logging and filename handling.
Please remove your old install and try the latest update.

Log files are located in the root of the distro install folder.  If you have issues, you can zip-up the .log files and send them to me for a closer look.

Thanks,
D.

**Comment by ScarletLovell** [comment]
deciding to close this because i can't provide logs as I'm not using windows anymore.
Sorry about that.
