### ISSUE TITLE
pkcon -y install neon-all isn´t  working anymore:

### ISSUE THREAD

**Issue by erstert3st** [DesktopECHO/kWSL#31]
Fatal error: The following packages have unmet dependencies:
  kpim6-libksieve: Depends: qt6-webengine (>= 6.7.0) but 6.6.3-0xneon+22.04+jammy+release+build32 is to be installed
  neochat: Depends: qt6-webview (>= 6.7.0) but 6.6.3-0xneon+22.04+jammy+release+build20 is to be installed
  kalgebra: Depends: qt6-webengine (>= 6.7.0) but 6.6.3-0xneon+22.04+jammy+release+build32 is to be installed
  kpim6-kdepim-runtime: Depends: qt6-webengine (>= 6.7.0) but 6.6.3-0xneon+22.04+jammy+release+build32 is to be installed
  konqueror: Depends: qt6-webengine (>= 6.7.0) but 6.6.3-0xneon+22.04+jammy+release+build32 is to be installed
  kontact: Depends: qt6-webengine (>= 6.7.0) but 6.6.3-0xneon+22.04+jammy+release+build32 is to be installed
           Recommends: akregator but it is not installable
           Recommends: kmail but it is not installable
  parley: Depends: qt6-webengine (>= 6.7.0) but 6.6.3-0xneon+22.04+jammy+release+build32 is to be installed
  neon-all: Depends: khelpcenter but it is not installable
  kpim6-messagelib: Depends: qt6-webengine (>= 6.7.0) but 6.6.3-0xneon+22.04+jammy+release+build32 is to be installed

Things i done already: 
pkcon update 
*worked only after i installed some packages manuell with pkcon

**Comment by DesktopECHO** [comment]
If you are on WSL2 run:

`sudo apt-mark unhold kactivitymanagerd libkf6activitiesstats1 plasma-activities-stats qt6-webengine qt6-webview`

...and you'll be able to install `neon-all`

If you are on WSL1, you won't be able to install `neon-all` until I release updated packages to disable WAL in sqlite.
