### ISSUE TITLE
XRDP broken after upgrade

### ISSUE THREAD

**Issue by NullDev** [DesktopECHO/kWSL#32]
While kWSL was running for like half a year now without issues, a recent KDE update from `sudo apt dist-upgrade` seemed to have broken xrdp. I am not sure if it's a kWSL specific issue or an XRDP issue but I'm in contact with them here:

https://github.com/neutrinolabs/xrdp/discussions/3153

**Comment by DesktopECHO** [comment]
Not sure what's happening -- You may want to try deploying a new instance and see how it behaves after updating.
