### ISSUE TITLE
Errors during installation

### ISSUE THREAD

**Issue by Haruno19** [DesktopECHO/kWSL#6]
I'm getting errors running the installation command.
I'm on Windows 10 Pro build 19042.685.
I'll attach a screeenshot and the only not-empty log file.

![errors](https://user-images.githubusercontent.com/61376940/101989612-ceb06500-3ca1-11eb-86ad-1294c9b497d6.png)

[173808 kWSL Inputs.log](https://github.com/DesktopECHO/kWSL/files/5683435/173808.kWSL.Inputs.log)

**Comment by DesktopECHO** [comment]
Hi there, delete the contents of your %TEMP% folder, run the Uninstaller as administrator and re-launch the script.

**Comment by DesktopECHO** [comment]
One more thing... if you scroll up and can show the console output from the beginning of the script I may get additional clues to what happened.  Seems like the distro download failed but cannot be sure.

**Comment by Haruno19** [comment]
Hi! Thanks, it works now, I probably had an issue with the download the first time I did it (as it took like twice as long this time), and without cleaning the Temp I kept getting those errors. Thank you so much!

**Comment by DesktopECHO** [comment]
Great news!  Hope you find it useful.
D.
